usr/bin/fsharpc
usr/bin/fsharpi
usr/lib/mono/Microsoft?F#
usr/lib/mono/Microsoft?SDKs
usr/lib/mono/xbuild
usr/lib/mono/fsharp/fs*.exe										/usr/lib/mono/fsharp
usr/lib/mono/fsharp/fs*.exe.config										/usr/lib/mono/fsharp
usr/lib/mono/fsharp/System.*.dll									/usr/lib/mono/fsharp
usr/lib/mono/fsharp/*.Targets										/usr/lib/mono/fsharp
usr/lib/mono/fsharp/FSharp.Compiler*.dll*								/usr/lib/mono/fsharp
